/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ArgumentsDecoderTestInterface extends utils.Interface {
  contractName: "ArgumentsDecoderTest";
  functions: {
    "fBool()": FunctionFragment;
    "fUint()": FunctionFragment;
    "testDecodeBool()": FunctionFragment;
    "testDecodeUint()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "fBool", values?: undefined): string;
  encodeFunctionData(functionFragment: "fUint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testDecodeBool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testDecodeUint",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "fBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testDecodeBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testDecodeUint",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ArgumentsDecoderTest extends BaseContract {
  contractName: "ArgumentsDecoderTest";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArgumentsDecoderTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fBool(overrides?: CallOverrides): Promise<[boolean]>;

    fUint(overrides?: CallOverrides): Promise<[BigNumber]>;

    testDecodeBool(overrides?: CallOverrides): Promise<[void]>;

    testDecodeUint(overrides?: CallOverrides): Promise<[void]>;
  };

  fBool(overrides?: CallOverrides): Promise<boolean>;

  fUint(overrides?: CallOverrides): Promise<BigNumber>;

  testDecodeBool(overrides?: CallOverrides): Promise<void>;

  testDecodeUint(overrides?: CallOverrides): Promise<void>;

  callStatic: {
    fBool(overrides?: CallOverrides): Promise<boolean>;

    fUint(overrides?: CallOverrides): Promise<BigNumber>;

    testDecodeBool(overrides?: CallOverrides): Promise<void>;

    testDecodeUint(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    fBool(overrides?: CallOverrides): Promise<BigNumber>;

    fUint(overrides?: CallOverrides): Promise<BigNumber>;

    testDecodeBool(overrides?: CallOverrides): Promise<BigNumber>;

    testDecodeUint(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fBool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fUint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testDecodeBool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testDecodeUint(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
